package com.cqnu.dlzf.bean;

import java.util.Date;
import java.util.List;

public class User {

    @Override
    public String toString() {
        return "User{" +
                "friends=" + friends +
                ", userId='" + userId + '\'' +
                ", ip='" + ip + '\'' +
                ", port=" + port +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", nickname='" + nickname + '\'' +
                ", image='" + image + '\'' +
                ", gender='" + gender + '\'' +
                ", birthday=" + birthday +
                ", bloodType='" + bloodType + '\'' +
                ", sign='" + sign + '\'' +
                ", job='" + job + '\'' +
                ", company='" + company + '\'' +
                ", location='" + location + '\'' +
                ", hometown='" + hometown + '\'' +
                ", telephone='" + telephone + '\'' +
                ", email='" + email + '\'' +
                ", state=" + state +
                '}';
    }

    private List<User> friends;

    private String userId;

    private String ip;

    private Integer port;

    private String username;

    private String password;

    private String nickname;

    private String image;

    private String gender;

    private Date birthday;

    private String bloodType;

    private String sign;

    private String job;

    private String company;

    private String location;

    private String hometown;

    private String telephone;

    private String email;

    private Integer state;

    public User() {
    }

    public User(String userId) {
        this.userId = userId;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Integer getPort() {
        return port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public List<User> getFriends() {
        return friends;
    }

    public void setFriends(List<User> friends) {
        this.friends = friends;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.nickname
     *
     * @return the value of t_user.nickname
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.nickname
     *
     * @param nickname the value for t_user.nickname
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.image
     *
     * @return the value of t_user.image
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.image
     *
     * @param image the value for t_user.image
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.gender
     *
     * @return the value of t_user.gender
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.gender
     *
     * @param gender the value for t_user.gender
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.birthday
     *
     * @return the value of t_user.birthday
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.birthday
     *
     * @param birthday the value for t_user.birthday
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.blood_type
     *
     * @return the value of t_user.blood_type
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.blood_type
     *
     * @param bloodType the value for t_user.blood_type
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType == null ? null : bloodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.sign
     *
     * @return the value of t_user.sign
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.sign
     *
     * @param sign the value for t_user.sign
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.job
     *
     * @return the value of t_user.job
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.job
     *
     * @param job the value for t_user.job
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.company
     *
     * @return the value of t_user.company
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.company
     *
     * @param company the value for t_user.company
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.location
     *
     * @return the value of t_user.location
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.location
     *
     * @param location the value for t_user.location
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.hometown
     *
     * @return the value of t_user.hometown
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getHometown() {
        return hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.hometown
     *
     * @param hometown the value for t_user.hometown
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setHometown(String hometown) {
        this.hometown = hometown == null ? null : hometown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.telephone
     *
     * @return the value of t_user.telephone
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.telephone
     *
     * @param telephone the value for t_user.telephone
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbg.generated Tue Dec 21 13:25:28 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}